# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-website-service
  labels:
    app: website
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: website
    release: {{ .Release.Name }}
